<?php
    require 'functions.php';

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Smartphone</title>
    
    <link rel="stylesheet" href="css/templatemo-prism-flux.css">

</head>
<body>
    <!-- Navigation Header -->
    <header class="header" id="header">
        <nav class="nav-container">
            
            <ul class="nav-menu" id="navMenu">
                <li><a href="login.php" class="nav-link">Login</a></li>
            </ul>

            <ul class="nav-menu" id="navMenu">
                <li><a href="register.php" class="nav-link">Register</a></li>
            </ul>
            
            <div class="menu-toggle" id="menuToggle">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </nav>
    </header>

    <!-- Hero Section with 3D Carousel -->
    <section class="hero" id="home">
        <div class="carousel-container">
            <div class="carousel" id="carousel">
                <!-- Carousel items will be generated by JavaScript -->
            </div>
            
            <div class="carousel-controls">
                <button class="carousel-btn" id="prevBtn">‹</button>
                <button class="carousel-btn" id="nextBtn">›</button>
            </div>
            
            <div class="carousel-indicators" id="indicators">
                <!-- Indicators will be generated by JavaScript -->
            </div>
        </div>
    </section>

    <script src="js/jquery-3.7.1.min.js"></script>
    <script src="js/script.js"></script>
    <script src="js/templatemo-prism-scripts.js"></script>
</body>
</html>